# A job is a set of steps in a workflow that execute on the same runner (a runner is a server that runs your workflows when triggered). 
# Workflows have jobs, and jobs have steps. 
# Steps are executed in order and are dependent on each other
# Actions steps run - in the order they are specified, from the top down - when a workflow job is processed. Each step must pass for the next step to run
# Each step consists of either a shell script that's executed, or a reference to an action that's run. 
# When we talk about an action (with a lowercase "a") in this context, we mean a reusable unit of code

# gives your workflow a name. This name will appear in the Actions tab of your repository
name: Post welcome comment
on:
  pull_request:
    # indicates that your workflow will execute whenever someone opens a pull request in your repository
    types: [opened]
# assigns the workflow permissions to operate on the repository
permissions:
  # gives the workflow permission to write to pull requests. This is needed to create the welcome comment
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    # fastest and cheapest job runner available
    runs-on: ubuntu-latest
    steps:
      # use GitHub CLI (gh) to add a comment when a pull request is opened. 
      # To allow GitHub CLI to post a comment, we set the GITHUB_TOKEN environment variable to the value of the GITHUB_TOKEN secret
      # - is an installation access token, created when the workflow runs. 
      # We set the PR_URL environment variable to the URL of the newly created pull request, and we use this in the gh command
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
